# Generated by Django 3.0.3 on 2020-02-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('payer', models.CharField(blank=True, max_length=100, null=True)),
                ('initialisation_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('payment_currency', models.CharField(blank=True, max_length=3)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('uid', models.UUIDField()),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'initiated'), (2, 'successful'), (3, 'failed'), (4, 'refund initiated'), (5, 'refunded')], default=1)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.Bank')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
