# Generated by Django 3.0.3 on 2020-02-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('payer', models.CharField(default='', max_length=100)),
                ('initialisation_time', models.DateTimeField(auto_now=True)),
                ('completion_time', models.DateTimeField(default='')),
                ('merchant_currency', models.CharField(max_length=3)),
                ('merchant_amount', models.DecimalField(decimal_places=2, default='', max_digits=25)),
                ('payment_currency', models.CharField(default='', max_length=3)),
                ('payment_amount', models.DecimalField(decimal_places=2, default='', max_digits=25)),
                ('payment_method', models.CharField(default='', max_length=50)),
                ('reference_number', models.CharField(default='', max_length=100)),
                ('international', models.BooleanField(default=False)),
                ('order_id', models.CharField(default='', max_length=50)),
                ('customer', models.CharField(default='', max_length=100)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'initiated'), (2, 'payment initiated'), (3, 'successful'), (4, 'failed'), (5, 'refund initiated'), (6, 'refunded')], default=1)),
                ('detail', models.CharField(default='', max_length=255)),
                ('bank', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.Bank')),
                ('payee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType')),
            ],
        ),
    ]
