# Generated by Django 3.0.3 on 2020-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
    ]
