# Generated by Django 3.0.3 on 2020-02-15 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='customer',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transaction.PaymentRequest'),
        ),
    ]
