# Generated by Django 3.0.3 on 2020-02-15 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0002_auto_20200215_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_request',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
