# Generated by Django 3.0.3 on 2020-02-15 05:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0004_merchant_is_active'),
        ('transaction', '0004_auto_20200215_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25)),
                ('method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=50)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.Payer')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_app',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='time',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction',
        ),
        migrations.AddField(
            model_name='payment',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='payment',
            name='initialisation_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AddField(
            model_name='payment',
            name='merchant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.Merchant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'initiated'), (2, 'successful'), (3, 'failed'), (4, 'refund initiated'), (5, 'refunded')], default=1),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='transaction.Payment'),
        ),
        migrations.AddField(
            model_name='paymentdetail',
            name='payment_app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.PaymentApp'),
        ),
    ]
