# Generated by Django 3.0.3 on 2020-02-15 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20200215_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='merchant',
        ),
    ]
