# Generated by Django 3.0.3 on 2020-02-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merchant_is_active'),
        ('transaction', '0006_remove_payment_merchant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='payment_app',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_app',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='user.PaymentApp'),
            preserve_default=False,
        ),
    ]
