# Generated by Django 3.0.3 on 2020-02-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_paymentapp_is_active'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('transaction', '0008_auto_20200215_0650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='Transaction',
        ),
        migrations.RenameField(
            model_name='paymentdetail',
            old_name='payment',
            new_name='transaction',
        ),
    ]
