# Generated by Django 3.0.3 on 2020-02-15 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20200215_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'initiated'), (2, 'successful')], default=1),
        ),
    ]
