# Generated by Django 3.0.3 on 2020-02-15 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_paymentrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paymentdetail',
            name='method',
        ),
    ]
