# Generated by Django 3.0.3 on 2020-02-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20200215_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetail',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
            preserve_default=False,
        ),
    ]
