# Generated by Django 3.0.3 on 2020-02-15 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0012_paymentdetail_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetail',
            name='completion_time',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
