# Generated by Django 3.0.3 on 2020-02-15 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_auto_20200215_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrequest',
            name='status',
        ),
    ]
