# Generated by Django 3.0.3 on 2020-02-15 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_paymentrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetail',
            name='transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transaction.PaymentDetail'),
        ),
    ]
