# Generated by Django 3.0.3 on 2020-02-09 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('business_address', models.CharField(max_length=255)),
                ('business_area', models.CharField(max_length=255)),
                ('business_pincode', models.CharField(max_length=20, unique=True)),
                ('business_city', models.CharField(max_length=25)),
                ('business_state', models.CharField(max_length=25)),
                ('business_country', models.CharField(max_length=25)),
                ('website', models.URLField()),
                ('owner_name', models.CharField(max_length=255)),
                ('business_category', models.PositiveSmallIntegerField(choices=[(1, 'Entertainment')])),
                ('pan_or_tin', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.CharField(max_length=255)),
                ('business_area', models.CharField(max_length=255)),
                ('business_pincode', models.CharField(max_length=20, unique=True)),
                ('business_city', models.CharField(max_length=25)),
                ('business_state', models.CharField(max_length=25)),
                ('business_country', models.CharField(max_length=25)),
                ('owner_name', models.CharField(max_length=255)),
                ('business_category', models.PositiveSmallIntegerField(choices=[(1, 'Entertainment')])),
                ('pan_or_tin', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=25)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
