# Generated by Django 3.0.3 on 2020-02-17 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
            preserve_default=False,
        ),
    ]
