# Generated by Django 3.0.3 on 2020-02-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_auto_20200215_0528'),
        ('user', '0002_auto_20200214_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
