# Generated by Django 3.0.3 on 2020-02-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
