# Generated by Django 3.0.3 on 2020-02-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_merchant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentapp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
