# Generated by Django 3.0.3 on 2020-02-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_paymentapp_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
    ]
