# Generated by Django 3.0.2 on 2020-02-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200204_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'undefined'), (1, 'admin'), (2, 'shops'), (3, 'websites'), (4, 'apps')], default=0),
        ),
    ]
