# Generated by Django 3.0.2 on 2020-02-05 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'shops'), (3, 'websites'), (4, 'banks')], default=1),
        ),
        migrations.AlterField(
            model_name='shop',
            name='mobile_number',
            field=models.IntegerField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_pincode',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=4)),
                ('mobile_number', models.IntegerField(max_length=20, unique=True)),
                ('business_name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('owner_name', models.CharField(max_length=255)),
                ('shop_category', models.PositiveSmallIntegerField(choices=[(1, 'Entertainment')])),
                ('pan_or_tin', models.CharField(max_length=100, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=4)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
