# Generated by Django 3.0.2 on 2020-02-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200205_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='mobile_number',
            field=models.IntegerField(unique=True),
        ),
    ]
